controller_list:
  - name: fake_fanucM35_controller
    joints:
      - joint1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
initial:  # Define initial robot poses.
  - group: fanucM35
    pose: home